$base  = (Get-Content "$PSScriptRoot\version.txt" -Raw).Trim()
$count = (& git -C "$PSScriptRoot" rev-list --count HEAD 2>$null).Trim()
$hash  = (& git -C "$PSScriptRoot" rev-parse --short HEAD 2>$null).Trim()
if (-not $count) { $count = "0" }
if (-not $hash)  { $hash  = "dev" }
$version = "$base.$count"
$full    = "$version ($hash)"
$content = @"
// Auto-generated by gen-version.ps1 - do not edit.
namespace Miner49er;
public static class GameVersion
{
    public const string Version = "$version";
    public const string Full    = "$full";
}
"@
[IO.File]::WriteAllText("$PSScriptRoot\game\GameVersion.g.cs", $content, [Text.Encoding]::UTF8)
Write-Host "Version: $full"
