namespace Miner49er.Core;

public abstract record SimEvent;
public sealed record MinerMoved(int MinerId, GridPos From, GridPos To) : SimEvent;
public sealed record ActivityStarted(int MinerId, ActivityKind Kind, GridPos Target) : SimEvent;
public sealed record RockMined(int MinerId, GridPos Pos, bool WasGold) : SimEvent;
public sealed record ChargePlanted(int MinerId, GridPos WallPos) : SimEvent;
public sealed record Explosion(GridPos WallPos, IReadOnlyList<GridPos> DestroyedRock) : SimEvent;
public sealed record MinerKilled(int MinerId) : SimEvent;
public sealed record MinerDrowned(int MinerId) : SimEvent;
public sealed record MinerFell(int MinerId) : SimEvent;
public sealed record MinerCrushed(int MinerId) : SimEvent;
public sealed record CrackWeakened(GridPos Pos) : SimEvent;
public sealed record CrackCollapsed(GridPos Pos) : SimEvent;
public sealed record MinerBurned(int MinerId) : SimEvent;
public sealed record LavaSpread(GridPos Pos) : SimEvent;
public sealed record LavaQuenched(GridPos Pos) : SimEvent;
public sealed record MinerReachedCenter(int MinerId) : SimEvent;
public sealed record TileFlooded(GridPos Pos, TileType Type) : SimEvent;
public sealed record ItemPickedUp(int MinerId, GridPos Pos, ItemKind Kind) : SimEvent;
public sealed record ItemUnburied(GridPos Pos, ItemKind Kind) : SimEvent;
public sealed record PlankPlaced(GridPos Pos) : SimEvent;
public sealed record MoldDropped(GridPos Pos) : SimEvent;
public sealed record MoldExpired(GridPos Pos) : SimEvent;
public sealed record MonsterMoved(int MonsterId, GridPos From, GridPos To) : SimEvent;
