namespace Miner49er.Core;

public abstract record SimEvent;
public sealed record MinerMoved(int MinerId, GridPos From, GridPos To) : SimEvent;
public sealed record ActivityStarted(int MinerId, ActivityKind Kind, GridPos Target) : SimEvent;
public sealed record RockMined(int MinerId, GridPos Pos, bool WasGold) : SimEvent;
public sealed record ChargePlanted(int MinerId, GridPos WallPos) : SimEvent;
public sealed record Explosion(GridPos WallPos, IReadOnlyList<GridPos> DestroyedRock) : SimEvent;
public sealed record MinerKilled(int MinerId) : SimEvent;
public sealed record MinerDrowned(int MinerId) : SimEvent;
public sealed record MinerFell(int MinerId) : SimEvent;
public sealed record MinerCrushed(int MinerId) : SimEvent;
public sealed record CrackWeakened(GridPos Pos) : SimEvent;
public sealed record CrackCollapsed(GridPos Pos) : SimEvent;
public sealed record MinerBurned(int MinerId) : SimEvent;
public sealed record LavaSpread(GridPos Pos) : SimEvent;
public sealed record LavaQuenched(GridPos Pos) : SimEvent;
public sealed record MinerReachedCenter(int MinerId) : SimEvent;
public sealed record TileFlooded(GridPos Pos, TileType Type) : SimEvent;
public sealed record ItemPickedUp(int MinerId, GridPos Pos, ItemKind Kind) : SimEvent;
public sealed record ItemUnburied(GridPos Pos, ItemKind Kind) : SimEvent;
public sealed record PlankPlaced(GridPos Pos) : SimEvent;
public sealed record MoldDropped(GridPos Pos) : SimEvent;
public sealed record MoldExpired(GridPos Pos) : SimEvent;
public sealed record MonsterMoved(int MonsterId, GridPos From, GridPos To) : SimEvent;
public sealed record MinerMauled(int MinerId) : SimEvent;
public sealed record MonsterKilled(int MonsterId) : SimEvent;
public sealed record EscapeOpened : SimEvent;
public sealed record LifeRestored(int MinerId) : SimEvent;
public sealed record StoneThrown(int MinerId, GridPos LandingPos) : SimEvent;
public sealed record DynamiteThrown(int MinerId, GridPos LandingPos) : SimEvent;
public sealed record DetonatorPlanted(int MinerId, GridPos WallPos) : SimEvent;
public sealed record ReelDetonated(int MinerId, GridPos WallPos) : SimEvent;
public sealed record ReelSnapped(int MinerId) : SimEvent;
public sealed record TreasureChestPlaced(int MinerId, GridPos Pos) : SimEvent;
public sealed record IdolDeposited(int MinerId, ItemKind Kind) : SimEvent;
public sealed record TripMinePlanted(int MinerId, GridPos Pos) : SimEvent;
public sealed record TripMineTriggered(int OwnerId, int TriggeredById, GridPos Pos) : SimEvent;
public sealed record MinerStunned(int AttackerId, int TargetId) : SimEvent;
public sealed record MonsterStunned(int AttackerId, int MonsterId) : SimEvent;
public sealed record RockFallWarned(GridPos Pos) : SimEvent;
public sealed record RockFell(GridPos Pos) : SimEvent;
public sealed record SkeletonAroused(int MonsterId) : SimEvent;
public sealed record CrystalShardDropped(GridPos Pos) : SimEvent;
public sealed record ScreeCollapsed(GridPos Pos, int Radius) : SimEvent;
public sealed record PortalUsed(int MinerId, GridPos From, GridPos To, PortalKind Kind) : SimEvent;
public sealed record PrizeTelegraphed(PrizeType Type, GridPos Pos) : SimEvent;
public sealed record PrizeClaimed(int MinerId, PrizeType Type) : SimEvent;
public sealed record PrizeExpired : SimEvent;
public sealed record TreasureFound(int MinerId) : SimEvent;
public sealed record TreasureRecovered(int MinerId) : SimEvent;
public sealed record TreasureSneaking(int MinerId) : SimEvent;
public sealed record TreasureDropped(int MinerId) : SimEvent;
